/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FundRaisingRole;

import Business.EcoSystem;
import Business.FundRaising.FundRaising;
import Business.FundRaising.Funds;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sujay
 */
public class FundRaisingCausesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundRaisingCausesJPanel
     */
    EcoSystem system;
    Funds funds;
    JPanel userProcessContainer;
    UserAccount ua;
    public FundRaisingCausesJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.ua = ua;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateCausesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFundDesc = new javax.swing.JTextField();
        btnAddService = new javax.swing.JButton();
        lblFundDesc = new javax.swing.JLabel();
        txtFundsRequired = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFunds = new javax.swing.JTable();
        lblFundName = new javax.swing.JLabel();
        txtFundName = new javax.swing.JTextField();
        lblFundsRequired = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtFundType = new javax.swing.JTextField();
        lblFundType = new javax.swing.JLabel();

        btnAddService.setText("Add Fund Raising Event");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        lblFundDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFundDesc.setText("Description :");

        tblFunds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fund Name", "Description", "Fund Required", "Fund Raiser Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFunds);

        lblFundName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFundName.setText("Fund Name :");

        lblFundsRequired.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFundsRequired.setText("Amount :");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFundType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFundType.setText("Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFundsRequired)
                                    .addComponent(lblFundDesc)
                                    .addComponent(lblFundName))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFundName)
                                    .addComponent(txtFundDesc)
                                    .addComponent(txtFundsRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAddService)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFundType)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtFundType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFundName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFundName))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFundDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFundDesc))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFundsRequired)
                    .addComponent(txtFundsRequired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFundType)
                    .addComponent(txtFundType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddService)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
        String name = txtFundName.getText();
        String desc = txtFundDesc.getText();
        int amount = Integer.parseInt(txtFundsRequired.getText());
        String type = txtFundType.getText();

        try {
            if(name == null || name.isEmpty()){
                throw new NullPointerException("Fund Name field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Fund Name field cannot be Empty !!!");
            return;
        }

        try {
            if(desc==null || desc.isEmpty()){
                throw new NullPointerException("Description field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Description field cannot be Empty !!!");
            return;
        }
        
        try {
            if(type==null || type.isEmpty()){
                throw new NullPointerException("Type field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Type field cannot be Empty !!!");
            return;
        }

        try {
            if(amount==0){
                throw new NullPointerException("Amount Field cannot be empty !!!");
            }
//            else if(Pattern.matches("^[0-9]{0,6}$", amount) == false){
//                throw new Exception("Invalid Amount !!!");
//            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Amount Field cannot be empty !!!");
            return;
        }
//        catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Invalid Amount !!!");
//            return;
//        }
        

        for(FundRaising fundRaising:system.getFundRaisingDirectory().getFundRaisingList()){
            if(fundRaising.getUserName().equals(ua.getUsername())){
                funds = system.getFundRaisingDirectory().addFundsTypes(fundRaising, name, desc, type, amount);
            }
        }

        txtFundName.setText("");
        txtFundDesc.setText("");
        txtFundsRequired.setText("");
        txtFundType.setText("");
        populateCausesTable();
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateCausesTable() {
        DefaultTableModel model = (DefaultTableModel) tblFunds.getModel();
        model.setRowCount(0);

        for (FundRaising fundRaising:system.getFundRaisingDirectory().getFundRaisingList()) {
            if (fundRaising.getUserName().equals(ua.getUsername())) {
               for(Funds fund: fundRaising.getFundList()){
                Object[] row = new Object[4];
                row[0] = fund.getFundName();
                row[1] = fund.getFundDescription();
                row[2] = fund.getFundAmount();
                row[3] = fund.getFundType();
                model.addRow(row);
               } 
            } 
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFundDesc;
    private javax.swing.JLabel lblFundName;
    private javax.swing.JLabel lblFundType;
    private javax.swing.JLabel lblFundsRequired;
    private javax.swing.JTable tblFunds;
    private javax.swing.JTextField txtFundDesc;
    private javax.swing.JTextField txtFundName;
    private javax.swing.JTextField txtFundType;
    private javax.swing.JTextField txtFundsRequired;
    // End of variables declaration//GEN-END:variables
}
