/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FundRaisingRole;
import Business.EcoSystem;
import Business.FundRaising.FundRaising;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author sujay
 */
public class ManageFundRaisingInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFundRaisingInfoJPanel
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    
    public ManageFundRaisingInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtFundRaisingName.setEnabled(false);
        txtFundRaisingAddress.setEnabled(false);
        txtFundRaisingPhNum.setEnabled(false);
        txtFundRaisingEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateInfoFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFundRaisingName = new javax.swing.JTextField();
        txtFundRaisingAddress = new javax.swing.JTextField();
        txtFundRaisingPhNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        titleFundRaisingOrg = new javax.swing.JLabel();
        lblFundRaisingEmail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtFundRaisingEmail = new javax.swing.JTextField();
        lblFundRaisingName = new javax.swing.JLabel();
        lblFundRaisingAddress = new javax.swing.JLabel();
        lblFundRaisingPhone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFundRaisingName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add(txtFundRaisingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 228, 200, -1));

        txtFundRaisingAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add(txtFundRaisingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 268, 200, -1));

        txtFundRaisingPhNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFundRaisingPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundRaisingPhNumActionPerformed(evt);
            }
        });
        add(txtFundRaisingPhNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 302, 200, -1));

        btnSave.setBackground(new java.awt.Color(133, 211, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 387, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(133, 211, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 387, -1, -1));

        titleFundRaisingOrg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        titleFundRaisingOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFundRaisingOrg.setText("Manage Fund Raising Org Info");
        add(titleFundRaisingOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, 1300, -1));

        lblFundRaisingEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblFundRaisingEmail.setText("Email:");
        add(lblFundRaisingEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 338, -1, -1));

        btnBack.setBackground(new java.awt.Color(133, 211, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 47, -1, -1));

        txtFundRaisingEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFundRaisingEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundRaisingEmailActionPerformed(evt);
            }
        });
        add(txtFundRaisingEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 335, 200, -1));

        lblFundRaisingName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblFundRaisingName.setText("Fund Raising Org Name :");
        add(lblFundRaisingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 231, -1, -1));

        lblFundRaisingAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblFundRaisingAddress.setText("Location:");
        add(lblFundRaisingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 271, -1, -1));

        lblFundRaisingPhone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblFundRaisingPhone.setText(" Phone Number :");
        add(lblFundRaisingPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 308, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/donate-image.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 500, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/donatehome.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 640, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFundRaisingPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundRaisingPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundRaisingPhNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtFundRaisingName.getText();
        String address = txtFundRaisingAddress.getText();
        String number = txtFundRaisingPhNum.getText();
        String email = txtFundRaisingEmail.getText();

        try {
            if(name==null || name.isEmpty()){
                throw new NullPointerException("Fund Raising Org Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Fund Raising Org Name Field cannot be Empty !!!");
            return;
        }

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("Fund Raising Org Address Field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Fund Raising Org Address Field cannot be Empty !!!");
            return;
        }

        try {

            if(number==null || number.isEmpty()){
                throw new NullPointerException("Fund Raising Org Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Fund Raising Org Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }

        try {
            if(email==null || email.isEmpty()){
                throw new NullPointerException("Fund Raising Org Email Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Fund Raising Org Email Field cannot be Empty !!!");
            return;
        }

        for(FundRaising fundRaising:system.getFundRaisingDirectory().getFundRaisingList()){
            if(fundRaising.getUserName().equals(account.getUsername())){
                system.getFundRaisingDirectory().updateFundRaisingInfo(fundRaising, name, number, address, email);
            }
        }

        txtFundRaisingName.setEnabled(false);
        txtFundRaisingAddress.setEnabled(false);
        txtFundRaisingPhNum.setEnabled(false);
        txtFundRaisingEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFundRaisingName.setEnabled(true);
        txtFundRaisingAddress.setEnabled(true);
        txtFundRaisingPhNum.setEnabled(true);
        txtFundRaisingEmail.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFundRaisingEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundRaisingEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundRaisingEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFundRaisingAddress;
    private javax.swing.JLabel lblFundRaisingEmail;
    private javax.swing.JLabel lblFundRaisingName;
    private javax.swing.JLabel lblFundRaisingPhone;
    private javax.swing.JLabel titleFundRaisingOrg;
    private javax.swing.JTextField txtFundRaisingAddress;
    private javax.swing.JTextField txtFundRaisingEmail;
    private javax.swing.JTextField txtFundRaisingName;
    private javax.swing.JTextField txtFundRaisingPhNum;
    // End of variables declaration//GEN-END:variables

    private void populateInfoFields() {
        for(FundRaising fundRaising:system.getFundRaisingDirectory().getFundRaisingList()){
           if(fundRaising.getUserName().equals(account.getUsername())){
               txtFundRaisingName.setText(fundRaising.getFundRaisingName());
               txtFundRaisingAddress.setText(fundRaising.getFundRaisingAddress());
               txtFundRaisingPhNum.setText(fundRaising.getFundRaisingPhNum());
               txtFundRaisingEmail.setText(fundRaising.getFundRaisingEmail());
            }
    }
    }
}
