/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MemberRole;

import Business.EcoSystem;
import Business.EmergencyDistressOrg.EmergencyDistressOrg;
import Business.EmergencyDistressOrg.EmergencyService;
import Business.Member.Member;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sujay
 */
public class EmergencyServiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmergencyServiceJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    EmergencyDistressOrg org;
    EcoSystem system;
    ArrayList<EmergencyService> services = new ArrayList<EmergencyService>();
    
    public EmergencyServiceJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, EmergencyDistressOrg org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = org;
        this.system = system;
        this.account = account;
        populateServicesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblServices = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCallAmbulance = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        txtIssue = new javax.swing.JTextField();
        lblIssue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Service Summary");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 307, -1, -1));

        lblServices.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblServices.setText("Emergency Service Details");
        add(lblServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        btnBack.setBackground(new java.awt.Color(133, 211, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 33, -1, -1));

        btnAdd.setBackground(new java.awt.Color(133, 211, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnAdd.setText("Add Service");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 266, -1, -1));

        btnRemove.setBackground(new java.awt.Color(133, 211, 255));
        btnRemove.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnRemove.setText("Remove Service");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        btnCallAmbulance.setBackground(new java.awt.Color(133, 211, 255));
        btnCallAmbulance.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnCallAmbulance.setText("Call Ambulance");
        btnCallAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallAmbulanceActionPerformed(evt);
            }
        });
        add(btnCallAmbulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, -1, -1));

        tblCart.setBackground(new java.awt.Color(133, 211, 255));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service", "Description", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCart);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 347, 552, 91));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setText("Pick Up Address :");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 540, -1, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 201, -1));

        tblServices.setBackground(new java.awt.Color(133, 211, 255));
        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service ", "Descripion", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblServices);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 157, 552, 91));

        txtIssue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        add(txtIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 502, 201, -1));

        lblIssue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIssue.setText("Emergency :");
        add(lblIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ambulancegif.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 570, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblServices.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Service to Add !!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            EmergencyService service = (EmergencyService)tblServices.getValueAt(selectedRow, 0);
            populateCartTable(service);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCart.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a Service to Remove!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            EmergencyService service = (EmergencyService)tblCart.getValueAt(selectedRow, 0);
            services.remove(service);
            DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
            model.setRowCount(0);
            Object[] row = new Object[3];
            for(EmergencyService req:services){
                row[0] = req;
                row[1] = req.getServiceDescription();
                row[2] = req.getServiceType();
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCallAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallAmbulanceActionPerformed
        // TODO add your handling code here:
        String address = txtAddress.getText();
        String issue = txtIssue.getText();

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("Please Enter Pickup Address !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter Pickup Address !!!");
            return;
        }
        
        try {
            if(issue==null || issue.isEmpty()){
                throw new NullPointerException("Please Enter the Emergency Reason !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter the Emergency Reason !!!");
            return;
        }

        org.newEmgRequest(org.getEmergencyOrgName(), account.getUsername(), null, services , address, issue);
        for(Member mem:system.getMemberDirectory().getMemberList()){
            if(account.getUsername().equals(mem.getMemUsername())){
                mem.newEmgRequest(org.getEmergencyOrgName(), account.getUsername(), null, services , address, issue);
            }
        }

        JOptionPane.showMessageDialog(null,"Your Request is placed Successfully !!!", "Thank You", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnCallAmbulanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCallAmbulance;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblIssue;
    private javax.swing.JLabel lblServices;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtIssue;
    // End of variables declaration//GEN-END:variables

    private void populateServicesTable() {
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.setRowCount(0);
            Object[] row = new Object[3];
            for(EmergencyService req:org.getServiceList()){
                 row[0] = req;
                 row[1] = req.getServiceDescription();
                 row[2] = req.getServiceType();
                 model.addRow(row);
            }  
    }

    private void populateCartTable(EmergencyService service) {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        model.setRowCount(0);

        services.add(service);
        
        Object[] row = new Object[3];
        for(EmergencyService req:services){
            row[0] = req;
            row[1] = req.getServiceDescription();
            row[2] = req.getServiceType();
            
            model.addRow(row);
        }  
    }
}
