/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MemberRole;

import Business.EcoSystem;
import Business.FundRaising.FundRaising;
import Business.Member.Member;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sujay
 */
public class FundDonationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount account;
    /**
     * Creates new form FundDonationJPanel
     */
    public FundDonationJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateFundOrgTable();
        populateDonationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFundRaisingOrg = new javax.swing.JTable();
        titleChoose = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        titleOrders = new javax.swing.JLabel();
        btnDonateFunds = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFundRaisingOrg.setBackground(new java.awt.Color(133, 211, 255));
        tblFundRaisingOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fund Raising Org Name", "Address", "Phone Number", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFundRaisingOrg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 737, 95));

        titleChoose.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        titleChoose.setText("Choose the Organization you want to donate for :");
        add(titleChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        tblRequests.setBackground(new java.awt.Color(133, 211, 255));
        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fund RaisingOrg Name", "Member Phone", "Amount Donated"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRequests);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 737, 90));

        titleOrders.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        titleOrders.setText("Your Donations to us :");
        add(titleOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        btnDonateFunds.setBackground(new java.awt.Color(133, 211, 255));
        btnDonateFunds.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDonateFunds.setText("Donate Funds");
        btnDonateFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateFundsActionPerformed(evt);
            }
        });
        add(btnDonateFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(133, 211, 255));
        btnRefresh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh Donations");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        btnBack.setBackground(new java.awt.Color(133, 211, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16147914.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 1070, 980));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonateFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateFundsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFundRaisingOrg.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            FundRaising fundRaisingOrg = (FundRaising) tblFundRaisingOrg.getValueAt(selectedRow, 0);
            DonationCausesJPanel donationCauses = new DonationCausesJPanel(userProcessContainer, account, system, fundRaisingOrg);
            userProcessContainer.add("Fund Raising Organization Service", donationCauses);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnDonateFundsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateDonationTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDonateFunds;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFundRaisingOrg;
    private javax.swing.JTable tblRequests;
    private javax.swing.JLabel titleChoose;
    private javax.swing.JLabel titleOrders;
    // End of variables declaration//GEN-END:variables

    private void populateFundOrgTable() {
        DefaultTableModel model = (DefaultTableModel) tblFundRaisingOrg.getModel();
        model.setRowCount(0);
        
            Object[] row = new Object[4];    
            for(FundRaising org:system.getFundRaisingDirectory().getFundRaisingList()){
                 row[0] = org;
                 row[1] = org.getFundRaisingAddress();
                 row[2] = org.getFundRaisingPhNum();
                 row[3] = org.getFundRaisingEmail();
                 model.addRow(row);
            }
    }

    public void populateDonationTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);

          for (Member mem:system.getMemberDirectory().getMemberList()) {   
            if (mem.getMemUsername().equals(account.getUsername())) {
               for(DonationRequest donation:mem.getDonationList()){
                Object[] row = new Object[3];
                row[0] = donation.getFundOrgName();
                row[1] = donation.getMemberPhNum();
                row[2] = donation.getTotalDonation();
                model.addRow(row);
               }            
            }  
        }
    }
}
