/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyDistressOrgRole;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.EmergencyDistressOrgRole.ManageEmergencyDistressInfoJPanel;

/**
 *
 * @author mohitdaswani
 */
public class EmergencyAdminWorkAreaJPanel extends javax.swing.JPanel {
   JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    /**
     * Creates new form EmergencyAdminWorkAreaJPanel
     */
    public EmergencyAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
      
        lblEmgName.setText(ua.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleResAdmin = new javax.swing.JLabel();
        btnOrgInfo = new javax.swing.JButton();
        btnManageServices = new javax.swing.JButton();
        btnManageRequests = new javax.swing.JButton();
        lblResNameTitle = new javax.swing.JLabel();
        lblEmgName = new javax.swing.JLabel();

        titleResAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleResAdmin.setText("Soup Kitchen Org Admin");

        btnOrgInfo.setText("Manage SnowClearingOrg Info");
        btnOrgInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgInfoActionPerformed(evt);
            }
        });

        btnManageServices.setText("Manage Services");
        btnManageServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageServicesActionPerformed(evt);
            }
        });

        btnManageRequests.setText("Manage Requests");
        btnManageRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestsActionPerformed(evt);
            }
        });

        lblResNameTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResNameTitle.setText("Soup Kitchen Name :");

        lblEmgName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addComponent(lblEmgName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(478, 478, 478))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(titleResAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblResNameTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btnManageRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btnManageServices, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(btnOrgInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(lblEmgName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleResAdmin)
                    .addGap(61, 61, 61)
                    .addComponent(lblResNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(btnManageRequests)
                    .addGap(27, 27, 27)
                    .addComponent(btnManageServices)
                    .addGap(27, 27, 27)
                    .addComponent(btnOrgInfo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgInfoActionPerformed
        // TODO add your handling code here:
        ManageEmergencyDistressInfoJPanel manageInfo = new ManageEmergencyDistressInfoJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Soup kitchen Organization Info",manageInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrgInfoActionPerformed

    private void btnManageServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageServicesActionPerformed
        ManageEmergencyServiceJPanel manageServices = new ManageEmergencyServiceJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Services",manageServices);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageServicesActionPerformed

    private void btnManageRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestsActionPerformed
        ManageEmergencyRequestsJPanel manageRequest = new ManageEmergencyRequestsJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Requests", manageRequest);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageRequests;
    private javax.swing.JButton btnManageServices;
    private javax.swing.JButton btnOrgInfo;
    private javax.swing.JLabel lblEmgName;
    private javax.swing.JLabel lblResNameTitle;
    private javax.swing.JLabel titleResAdmin;
    // End of variables declaration//GEN-END:variables
}
