/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyDistressOrgRole;
import Business.EcoSystem;
import Business.EmergencyDistressOrg.EmergencyDistressOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author mohitdaswani
 */
public class ManageEmergencyDistressInfoJPanel extends javax.swing.JPanel {
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    /**
     * Creates new form ManageEmergencyDistressInfoJPanel
     */
    public ManageEmergencyDistressInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOrgName = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        txtOrgPhNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        titleEmergencyOrg = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtOrgEmail = new javax.swing.JTextField();
        lblSnowClearningName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 234, 130, -1));
        add(txtOrgAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 272, 130, -1));

        txtOrgPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgPhNumActionPerformed(evt);
            }
        });
        add(txtOrgPhNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 306, 130, -1));

        btnSave.setBackground(new java.awt.Color(133, 211, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 387, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(133, 211, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 387, -1, -1));

        titleEmergencyOrg.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        titleEmergencyOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEmergencyOrg.setText("Manage Emergency Distress Org Info");
        add(titleEmergencyOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 1350, 36));

        lblEmail.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 338, -1, -1));

        btnBack.setBackground(new java.awt.Color(133, 211, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 47, -1, -1));

        txtOrgEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgEmailActionPerformed(evt);
            }
        });
        add(txtOrgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 337, 130, -1));

        lblSnowClearningName.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblSnowClearningName.setText("Emergency Org Name :");
        add(lblSnowClearningName, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 235, -1, -1));

        lblAddress.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblAddress.setText("Location:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 273, -1, -1));

        lblPhone.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblPhone.setText("Phone Number :");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ambulance.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 210, 850, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrgPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgPhNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtOrgName.getText();
        String address = txtOrgAddress.getText();
        String number = txtOrgPhNum.getText();
        String email = txtOrgEmail.getText();

        try {
            if(name==null || name.isEmpty()){
                throw new NullPointerException("Emergency Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Emergency Organizations Name Field cannot be Empty !!!");
            return;
        }

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("Emergency Organization Field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Emergency Organization Field cannot be Empty !!!");
            return;
        }

        try {

            if(number==null || number.isEmpty()){
                throw new NullPointerException("LeafClearingOrg Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Emergency Org Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }

        try {
            if(email==null || email.isEmpty()){
                throw new NullPointerException("Emergency Org Email Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Emergency Org Email Field cannot be Empty !!!");
            return;
        }

        for(EmergencyDistressOrg org:system.getEmergencyDistressOrgDirectory().getEmergencyDistressOrgList()){
            if(org.getUserName().equals(account.getUsername())){
                system.getEmergencyDistressOrgDirectory().updateEmergencyDistressOrgInfo(org, name, number, address, email);
            }
        }

        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtOrgName.setEnabled(true);
        txtOrgAddress.setEnabled(true);
        txtOrgPhNum.setEnabled(true);
        txtOrgEmail.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrgEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgEmailActionPerformed

    private void populateFields() {
        for(EmergencyDistressOrg org:system.getEmergencyDistressOrgDirectory().getEmergencyDistressOrgList()){
           if(org.getUserName().equals(account.getUsername())){
               txtOrgName.setText(org.getEmergencyOrgName());
               txtOrgAddress.setText(org.getEmergencyOrgAddress());
               txtOrgPhNum.setText(org.getEmergencyOrgPhNum());
               txtOrgEmail.setText(org.getEmergencyOrgEmail());
            }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSnowClearningName;
    private javax.swing.JLabel titleEmergencyOrg;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhNum;
    // End of variables declaration//GEN-END:variables
}
