

package userinterface.SnowClearingOrgRole;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.SnowClearingOrgRole.ManageSnowClearingInfoJPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
      
        lblResName.setText(ua.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleResAdmin = new javax.swing.JLabel();
        btnOrgInfo = new javax.swing.JButton();
        btnManageSeasons = new javax.swing.JButton();
        btnManageServices = new javax.swing.JButton();
        lblResNameTitle = new javax.swing.JLabel();
        lblResName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 156, 52));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleResAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleResAdmin.setText("SnowClearingOrg Admin");
        add(titleResAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnOrgInfo.setText("Manage SnowClearingOrg Info");
        btnOrgInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgInfoActionPerformed(evt);
            }
        });
        add(btnOrgInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, -1));

        btnManageSeasons.setText("Manage Seasons");
        btnManageSeasons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSeasonsActionPerformed(evt);
            }
        });
        add(btnManageSeasons, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, -1));

        btnManageServices.setText("Manage Services");
        btnManageServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageServicesActionPerformed(evt);
            }
        });
        add(btnManageServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, -1));

        lblResNameTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResNameTitle.setText("Restaurant Name :");
        add(lblResNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 190, 30));

        lblResName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        add(lblResName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgInfoActionPerformed
        // TODO add your handling code here:
        ManageSnowClearingInfoJPanel manageInfo = new ManageSnowClearingInfoJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Snow Clearning Organization Info",manageInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrgInfoActionPerformed

    private void btnManageSeasonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSeasonsActionPerformed
        ManageServiceJPanel manageMenu = new ManageServiceJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Seasons",manageMenu);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSeasonsActionPerformed

    private void btnManageServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageServicesActionPerformed
        ManageRequestsJPanel manageOrder = new ManageRequestsJPanel(userProcessContainer, ua, system);
        userProcessContainer.add("Manage Orders", manageOrder);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageServicesActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageSeasons;
    private javax.swing.JButton btnManageServices;
    private javax.swing.JButton btnOrgInfo;
    private javax.swing.JLabel lblResName;
    private javax.swing.JLabel lblResNameTitle;
    private javax.swing.JLabel titleResAdmin;
    // End of variables declaration//GEN-END:variables
    
}
