/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SnowClearingOrgRole;

import Business.Member.Member;
import Business.FieldWorker.FieldWorker;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sujay
 */
public class FieldWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FieldWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    WorkRequest request;
    EcoSystem system;
    
    public FieldWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, WorkRequest request, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.request = request;
        this.system = system;
        initComponents();
        populateFieldWorkers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FieldWorkerJTable = new javax.swing.JTable();
        btnAssignRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1360, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(133, 211, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assign FieldWorker");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 333, -1));

        FieldWorkerJTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        FieldWorkerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Field Worker Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FieldWorkerJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 360, 90));

        btnAssignRequest.setBackground(new java.awt.Color(133, 211, 255));
        btnAssignRequest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnAssignRequest.setText("Assign Request to the Selected FieldWorker");
        btnAssignRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRequestActionPerformed(evt);
            }
        });
        add(btnAssignRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shovel_guy.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 11, 1022, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = FieldWorkerJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            
            FieldWorker fieldWorker  = (FieldWorker)FieldWorkerJTable.getValueAt(selectedRow, 0);   
            fieldWorker.getRequestList().add(request);
            fieldWorker.setAvailability(false);
            request.setStatus("Assigned Field Worker");
            
            for(Member member:system.getMemberDirectory().getMemberList()){
            if(request.getMemName().equals(member.getMemUsername())){
                for(WorkRequest request : member.getRequestList()){
                    if(request.getStatus().equals("In Progress")){
                        request.setStatus("Assigned Field Worker");
                    }
                }
            }
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
            
        }
    }//GEN-LAST:event_btnAssignRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FieldWorkerJTable;
    private javax.swing.JButton btnAssignRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateFieldWorkers() {
        DefaultTableModel model = (DefaultTableModel) FieldWorkerJTable.getModel();
        model.setRowCount(0);
        
        for(FieldWorker fieldWorker:system.getFieldWorkerDirectory().getFieldWorkerList()){
            if(fieldWorker.getAvailability()==true){
               Object[] row = new Object[1];           
                row[0] = fieldWorker;
                model.addRow(row);
            }
            }
    }
}
