/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LeafClearingOrgRole;

import Business.EcoSystem;
import Business.LeafClearingOrg.LeafClearingOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ManageLeafClearingInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSnowClearingInfoJPanel
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    
    public ManageLeafClearingInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateFields();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblLeafClearingName = new javax.swing.JLabel();
        lblLeafClearingAddress = new javax.swing.JLabel();
        lblLeafClearingPhone = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        txtOrgPhNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtOrgEmail = new javax.swing.JTextField();
        lblImageIcon2 = new javax.swing.JLabel();
        titleSnowClearingOrg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1350, 780));

        btnBack.setBackground(new java.awt.Color(255, 204, 102));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblLeafClearingName.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblLeafClearingName.setText("LeafClearing Enterprize Name :");

        lblLeafClearingAddress.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblLeafClearingAddress.setText("LeafClearning Enterprize Address :");

        lblLeafClearingPhone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblLeafClearingPhone.setText("LeafClearing Phone Number :");

        txtOrgName.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtOrgName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOrgAddress.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtOrgAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOrgPhNum.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtOrgPhNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrgPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgPhNumActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 204, 102));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 204, 102));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        lblEmail.setText("Email:");

        txtOrgEmail.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtOrgEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrgEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgEmailActionPerformed(evt);
            }
        });

        lblImageIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_services_adobespark.png"))); // NOI18N
        lblImageIcon2.setText("jLabel2");

        titleSnowClearingOrg1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleSnowClearingOrg1.setForeground(new java.awt.Color(0, 0, 153));
        titleSnowClearingOrg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSnowClearingOrg1.setText("Manage Leaf Clearing Org Information");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LeafClearingOrg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(titleSnowClearingOrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblImageIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnSave))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLeafClearingPhone)
                                .addComponent(lblLeafClearingAddress)
                                .addComponent(lblLeafClearingName)
                                .addComponent(lblEmail))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrgPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrgAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtOrgAddress, txtOrgEmail, txtOrgName, txtOrgPhNum});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSnowClearingOrg1)
                .addGap(32, 32, 32)
                .addComponent(lblImageIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblLeafClearingName))
                    .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLeafClearingAddress)
                    .addComponent(txtOrgAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOrgPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeafClearingPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtOrgAddress, txtOrgEmail, txtOrgName, txtOrgPhNum});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrgPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgPhNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtOrgName.getText();
        String address = txtOrgAddress.getText();
        String number = txtOrgPhNum.getText();
       String email = txtOrgEmail.getText();
        
        try {
             if(name==null || name.isEmpty()){
                throw new NullPointerException("LeafClearingOrg Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Organizations Name Field cannot be Empty !!!");        
            return;   
        }
        
        try {
             if(address==null || address.isEmpty()){
                throw new NullPointerException("LeafClearing Organization Field cannot be Empty !!!");    
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Organization Field cannot be Empty !!!");          
            return;   
        }
        
         try {
             
            if(number==null || number.isEmpty()){
                throw new NullPointerException("LeafClearingOrg Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }     
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearingOrg Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }
         
        try {
             if(email==null || email.isEmpty()){
                throw new NullPointerException("LeafClearing Org Email Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Org Email Field cannot be Empty !!!");        
            return;   
        }
        
        for(LeafClearingOrg org:system.getLeafClearingOrgDirectory().getLeafClearingOrgList()){
           if(org.getUserName().equals(account.getUsername())){
                system.getLeafClearingOrgDirectory().updateLeafClearingOrgInfo(org, name, number, address, email);
            }
        }
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtOrgName.setEnabled(true);
        txtOrgAddress.setEnabled(true);
        txtOrgPhNum.setEnabled(true);
        txtOrgEmail.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtOrgEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImageIcon2;
    private javax.swing.JLabel lblLeafClearingAddress;
    private javax.swing.JLabel lblLeafClearingName;
    private javax.swing.JLabel lblLeafClearingPhone;
    private javax.swing.JLabel titleSnowClearingOrg1;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhNum;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        for(LeafClearingOrg org:system.getLeafClearingOrgDirectory().getLeafClearingOrgList()){
           if(org.getUserName().equals(account.getUsername())){
               txtOrgName.setText(org.getLeafOrgName());
               txtOrgAddress.setText(org.getLeafOrgAddress());
               txtOrgPhNum.setText(org.getLeafOrgPhNum());
               txtOrgEmail.setText(org.getLeafOrgEmail());
            }
    }
}
}
