/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LeafClearingOrgRole;

import Business.EcoSystem;
import Business.LeafClearingOrg.LeafClearingOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ManageLeafClearingInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSnowClearingInfoJPanel
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    
    public ManageLeafClearingInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateFields();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblLeafClearingName = new javax.swing.JLabel();
        lblLeafClearingAddress = new javax.swing.JLabel();
        lblLeafClearingPhone = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        txtOrgPhNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtOrgEmail = new javax.swing.JTextField();
        lblImageIcon2 = new javax.swing.JLabel();
        titleSnowClearingOrg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1350, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 204, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, -1, 30));

        lblLeafClearingName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblLeafClearingName.setText("LeafClearing Enterprize Name :");
        add(lblLeafClearingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        lblLeafClearingAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblLeafClearingAddress.setText("LeafClearing Enterprize Address :");
        add(lblLeafClearingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        lblLeafClearingPhone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblLeafClearingPhone.setText("LeafClearing Phone Number :");
        add(lblLeafClearingPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, -1, -1));

        txtOrgName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        txtOrgName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 280, 30));

        txtOrgAddress.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtOrgAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtOrgAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 280, 30));

        txtOrgPhNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        txtOrgPhNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrgPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgPhNumActionPerformed(evt);
            }
        });
        add(txtOrgPhNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 280, 30));

        btnSave.setBackground(new java.awt.Color(255, 204, 102));
        btnSave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, 102, 30));

        btnUpdate.setBackground(new java.awt.Color(255, 204, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 102, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, -1, -1));

        txtOrgEmail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        txtOrgEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrgEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgEmailActionPerformed(evt);
            }
        });
        add(txtOrgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 280, 30));

        lblImageIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_services_adobespark.png"))); // NOI18N
        lblImageIcon2.setText("jLabel2");
        add(lblImageIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 230, 190));

        titleSnowClearingOrg1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        titleSnowClearingOrg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSnowClearingOrg1.setText("Manage Leaf Clearing Org Information");
        add(titleSnowClearingOrg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 550, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LeafClearingOrg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 11, 1150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrgPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgPhNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtOrgName.getText();
        String address = txtOrgAddress.getText();
        String number = txtOrgPhNum.getText();
       String email = txtOrgEmail.getText();
        
        try {
             if(name==null || name.isEmpty()){
                throw new NullPointerException("LeafClearingOrg Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Organizations Name Field cannot be Empty !!!");        
            return;   
        }
        
        try {
             if(address==null || address.isEmpty()){
                throw new NullPointerException("LeafClearing Organization Field cannot be Empty !!!");    
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Organization Field cannot be Empty !!!");          
            return;   
        }
        
         try {
             
            if(number==null || number.isEmpty()){
                throw new NullPointerException("LeafClearingOrg Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }     
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearingOrg Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }
         
        try {
             if(email==null || email.isEmpty()){
                throw new NullPointerException("LeafClearing Org Email Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "LeafClearing Org Email Field cannot be Empty !!!");        
            return;   
        }
        
        for(LeafClearingOrg org:system.getLeafClearingOrgDirectory().getLeafClearingOrgList()){
           if(org.getUserName().equals(account.getUsername())){
                system.getLeafClearingOrgDirectory().updateLeafClearingOrgInfo(org, name, number, address, email);
            }
        }
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        txtOrgEmail.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtOrgName.setEnabled(true);
        txtOrgAddress.setEnabled(true);
        txtOrgPhNum.setEnabled(true);
        txtOrgEmail.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtOrgEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImageIcon2;
    private javax.swing.JLabel lblLeafClearingAddress;
    private javax.swing.JLabel lblLeafClearingName;
    private javax.swing.JLabel lblLeafClearingPhone;
    private javax.swing.JLabel titleSnowClearingOrg1;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhNum;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        for(LeafClearingOrg org:system.getLeafClearingOrgDirectory().getLeafClearingOrgList()){
           if(org.getUserName().equals(account.getUsername())){
               txtOrgName.setText(org.getLeafOrgName());
               txtOrgAddress.setText(org.getLeafOrgAddress());
               txtOrgPhNum.setText(org.getLeafOrgPhNum());
               txtOrgEmail.setText(org.getLeafOrgEmail());
            }
    }
}
}
