/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Member.Member;
import Business.FieldWorker.FieldWorker;
import Business.EcoSystem;

import Business.Organization;
import Business.SnowClearingOrg.SnowClearingOrg;
import Business.LeafClearingOrg.LeafClearingOrg;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnManageMembers2 = new javax.swing.JButton();
        btnManageSCOrg2 = new javax.swing.JButton();
        btnManageFieldWorkers2 = new javax.swing.JButton();
        titleManageUser2 = new javax.swing.JLabel();
        btnManageFRENT2 = new javax.swing.JButton();
        btnManageLCOrg3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(252, 156, 52));

        btnManageMembers2.setText("Manage Members");
        btnManageMembers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMembersActionPerformed(evt);
            }
        });

        btnManageSCOrg2.setText("Manage SnowClearing Enterprise");
        btnManageSCOrg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSCOrgActionPerformed(evt);
            }
        });

        btnManageFieldWorkers2.setText("Manage FieldWorker");
        btnManageFieldWorkers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFieldWorkersActionPerformed(evt);
            }
        });

        titleManageUser2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleManageUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageUser2.setText("Manage User Accounts and Credentials");

        btnManageFRENT2.setText("Manage FundRaising Enterprises");
        btnManageFRENT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFRENTActionPerformed(evt);
            }
        });

        btnManageLCOrg3.setText("Manage LeafClearing Enterprise");
        btnManageLCOrg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLCOrg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleManageUser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManageFRENT2)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManageFieldWorkers2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageSCOrg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageMembers2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnManageLCOrg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 655, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(titleManageUser2)
                .addGap(60, 60, 60)
                .addComponent(btnManageMembers2)
                .addGap(18, 18, 18)
                .addComponent(btnManageSCOrg2)
                .addGap(13, 13, 13)
                .addComponent(btnManageLCOrg3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageFieldWorkers2)
                .addGap(18, 18, 18)
                .addComponent(btnManageFRENT2)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageLCOrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLCOrg1ActionPerformed
        // TODO add your handling code here:
        ManageLeafClearingOrgJPanel manageLeafClearingOrgJPanel=new ManageLeafClearingOrgJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("Manage LeafClearingOrg",manageLeafClearingOrgJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageLCOrg1ActionPerformed

    private void btnManageFRENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFRENTActionPerformed
        // TODO add your handling code here:
        ManageFundRaisingJPanel manageFundRaisingJPanel=new ManageFundRaisingJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("Manage FundRaising Enterprises",manageFundRaisingJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageFRENTActionPerformed

    private void btnManageFieldWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFieldWorkersActionPerformed
        ManageFieldWorkerJPanel manageFieldWorkerJPanel=new ManageFieldWorkerJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("Manage FieldWorker",manageFieldWorkerJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageFieldWorkersActionPerformed

    private void btnManageSCOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSCOrgActionPerformed
        ManageSnowClearingOrgJPanel manageSnowClearingOrgJPanel=new ManageSnowClearingOrgJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("Manage SnowClearingOrg",manageSnowClearingOrgJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSCOrgActionPerformed

    private void btnManageMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMembersActionPerformed
        ManageMembersJPanel manageMembersJPanel=new ManageMembersJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("Manage Member",manageMembersJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMembersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageFRENT;
    private javax.swing.JButton btnManageFRENT2;
    private javax.swing.JButton btnManageFieldWorkers;
    private javax.swing.JButton btnManageFieldWorkers2;
    private javax.swing.JButton btnManageLCOrg1;
    private javax.swing.JButton btnManageLCOrg3;
    private javax.swing.JButton btnManageMembers;
    private javax.swing.JButton btnManageMembers2;
    private javax.swing.JButton btnManageSCOrg;
    private javax.swing.JButton btnManageSCOrg2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel titleManageUser;
    private javax.swing.JLabel titleManageUser2;
    // End of variables declaration//GEN-END:variables


}
