/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SoupKitchenOrgRole;

import Business.EcoSystem;
import Business.SoupKitchenOrg.SoupKitchenOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ManageSoupKitchenInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSoupKitchenInfoJPanel
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount account;
    public ManageSoupKitchenInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        
        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtOrgPhNum = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        txtOrgName = new javax.swing.JTextField();
        lblSoupKitchenPhone = new javax.swing.JLabel();
        lblSoupKitchenAddress = new javax.swing.JLabel();
        lblSoupKitchenName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblImageIcon2 = new javax.swing.JLabel();
        titleSnowClearingOrg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 111, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 102, -1));

        txtOrgPhNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtOrgPhNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrgPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgPhNumActionPerformed(evt);
            }
        });
        add(txtOrgPhNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 243, 34));

        txtOrgAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtOrgAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtOrgAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 243, 34));

        txtOrgName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtOrgName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 243, 34));

        lblSoupKitchenPhone.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblSoupKitchenPhone.setText("Soup Kitchen Phone Number :");
        add(lblSoupKitchenPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        lblSoupKitchenAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblSoupKitchenAddress.setText("Soup Kitchen Address :");
        add(lblSoupKitchenAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        lblSoupKitchenName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblSoupKitchenName.setText("Soup Kitchen Name :");
        add(lblSoupKitchenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 41, -1, 30));

        lblImageIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_services_adobespark.png"))); // NOI18N
        lblImageIcon2.setText("jLabel2");
        add(lblImageIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 230, 190));

        titleSnowClearingOrg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        titleSnowClearingOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSnowClearingOrg.setText("Manage Soup Kitchen Org Information");
        add(titleSnowClearingOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 422, 29));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManageSoupKitchen.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 684, 776));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtOrgName.setEnabled(true);
        txtOrgAddress.setEnabled(true);
        txtOrgPhNum.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtOrgName.getText();
        String address = txtOrgAddress.getText();
        String number = txtOrgPhNum.getText();

        try {
            if(name==null || name.isEmpty()){
                throw new NullPointerException("SnowClearingOrg Name Field cannot be Empty !!!");

            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "SnowClearing Organizations Name Field cannot be Empty !!!");
            return;
        }

        try {
            if(address==null || address.isEmpty()){
                throw new NullPointerException("SnowClearing Organization Field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "SnowClearing Organization Field cannot be Empty !!!");
            return;
        }

        try {

            if(number==null || number.isEmpty()){
                throw new NullPointerException("SnowClearingOrg Phone Number Field cannot be Empty !!!");
            }else if(Pattern.matches("^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$", number) == false){
                throw new Exception("Enter a Valid Phone number !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "SnowClearingOrg Phone Number Field cannot be Empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a Valid Phone number !!!");
            return;
        }


        for(SoupKitchenOrg org:system.getSoupKitchenOrgDirectory().getSoupKitchenList()){
            if(org.getUserName().equals(account.getUsername())){
                system.getSoupKitchenOrgDirectory().updateSoupInfo(org, name, number, address);
            }
        }

        txtOrgName.setEnabled(false);
        txtOrgAddress.setEnabled(false);
        txtOrgPhNum.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtOrgPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgPhNumActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImageIcon2;
    private javax.swing.JLabel lblSoupKitchenAddress;
    private javax.swing.JLabel lblSoupKitchenName;
    private javax.swing.JLabel lblSoupKitchenPhone;
    private javax.swing.JLabel titleSnowClearingOrg;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhNum;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        for(SoupKitchenOrg org:system.getSoupKitchenOrgDirectory().getSoupKitchenList()){
           if(org.getUserName().equals(account.getUsername())){
               txtOrgName.setText(org.getSoupName());
               txtOrgAddress.setText(org.getSoupLocation());
               txtOrgPhNum.setText(org.getSoupPhNum());
            }
    }
    }
}
