/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SoupKitchenOrgRole;

import Business.EcoSystem;
import Business.SoupKitchenOrg.Meal;
import Business.SoupKitchenOrg.SoupKitchenOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sujay
 */
public class ManageSoupKitchenServiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSoupKitchenServiceJPanel
     */
    EcoSystem system;
    Meal meal;
    JPanel userProcessContainer;
    UserAccount ua;
    public ManageSoupKitchenServiceJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.ua = ua;
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblBeverage = new javax.swing.JLabel();
        txtMealName = new javax.swing.JTextField();
        lblMealName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeal = new javax.swing.JTable();
        txtBeverage = new javax.swing.JTextField();
        lblMealDesc = new javax.swing.JLabel();
        btnAddMeal = new javax.swing.JButton();
        txtMealDesc = new javax.swing.JTextField();
        titleManageService = new javax.swing.JLabel();
        lblImageIcon3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        btnBack.setText("<< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 40));

        lblBeverage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblBeverage.setText("Beverage :");
        add(lblBeverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, -1, -1));

        txtMealName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtMealName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtMealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 297, 34));

        lblMealName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblMealName.setText("Meal Name :");
        add(lblMealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        tblMeal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Meal Name", "Description", "Beverage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMeal);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 368, 607, 122));

        txtBeverage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtBeverage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtBeverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 297, 37));

        lblMealDesc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblMealDesc.setText("Description :");
        add(lblMealDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        btnAddMeal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        btnAddMeal.setText("Add Meal");
        btnAddMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMealActionPerformed(evt);
            }
        });
        add(btnAddMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 680, -1, 40));

        txtMealDesc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtMealDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtMealDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 297, 38));

        titleManageService.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleManageService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageService.setText("Manage Soup Kitchen Menu");
        add(titleManageService, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 33, 526, -1));

        lblImageIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuSoup_adobespark.jpeg"))); // NOI18N
        lblImageIcon3.setText("jLabel2");
        add(lblImageIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 92, 301, 258));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vegSoup.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 651, 779));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMealActionPerformed
        // TODO add your handling code here:
        String name = txtMealName.getText();
        String desc = txtMealDesc.getText();
        String beverage = txtBeverage.getText();

        try {
            if(name == null || name.isEmpty()){
                throw new NullPointerException("Service Name field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Service Name field cannot be Empty !!!");
            return;
        }

        try {
            if(desc==null || desc.isEmpty()){
                throw new NullPointerException("Description field cannot be Empty !!!");
            }
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Description field cannot be Empty !!!");
            return;
        }

        try {
            if(beverage==null || beverage.isEmpty()){
                throw new NullPointerException("Beverage Field cannot be empty !!!");
            }
        }  catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Beverage Field cannot be empty !!!");
            return;
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Beverage !!!");
            return;
        }

        for(SoupKitchenOrg org:system.getSoupKitchenOrgDirectory().getSoupKitchenList()){
            if(org.getUserName().equals(ua.getUsername())){
                meal = system.getSoupKitchenOrgDirectory().addSoupMeal(org, name, desc, beverage);
            }
        }

        txtMealName.setText("");
        txtMealDesc.setText("");
        txtBeverage.setText("");
        populateTable();
    }//GEN-LAST:event_btnAddMealActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMeal;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBeverage;
    private javax.swing.JLabel lblImageIcon3;
    private javax.swing.JLabel lblMealDesc;
    private javax.swing.JLabel lblMealName;
    private javax.swing.JTable tblMeal;
    private javax.swing.JLabel titleManageService;
    private javax.swing.JTextField txtBeverage;
    private javax.swing.JTextField txtMealDesc;
    private javax.swing.JTextField txtMealName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblMeal.getModel();
        model.setRowCount(0);

        for (SoupKitchenOrg org:system.getSoupKitchenOrgDirectory().getSoupKitchenList()) {
            if (org.getUserName().equals(ua.getUsername())) {
               for(Meal meal: org.getMealList()){
                Object[] row = new Object[3];
                row[0] = meal.getMealName();
                row[1] = meal.getMealDescription();
                row[2] = meal.getBeverage();
                model.addRow(row);
               } 
            } 
        }
    }
}
