/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryVolunteerRole;

import Business.DeliveryVolunteer.DeliveryVolunteer;
import Business.EcoSystem;
import Business.Member.Member;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SoupWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ProcessOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessOrderJPanel
     */
    
    JPanel userProcessContainer;
    SoupWorkRequest request;
    EcoSystem system;
    UserAccount account;
    public ProcessOrderJPanel(JPanel userProcessContainer, SoupWorkRequest request, EcoSystem system,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system=system;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComplete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComplete.setBackground(new java.awt.Color(133, 211, 255));
        btnComplete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnComplete.setText("Delivered Soup Order");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 373, 273, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delivergif.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 560, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delivery.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 690, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        request.setStatus("Delivered");
        for(Member mem:system.getMemberDirectory().getMemberList()){
            if(request.getMemName().equals(mem.getMemUsername())){
                for(SoupWorkRequest request : mem.getSoupRequestList()){
                    if(request.getStatus().equals("Assigned Volunteer")) {
                        request.setStatus("Delivered");
                    }
                }
            }
        }
        for(DeliveryVolunteer volunteer : system.getDeliveryVolunteerDirectory().getVolunteerList()){
            if(volunteer.getVolunteerUsername().equals(account.getUsername())){
                volunteer.setAvailability(true);
            }
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
