/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryVolunteerRole;

import Business.DeliveryVolunteer.DeliveryVolunteer;
import Business.EcoSystem;
import Business.Member.Member;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SoupWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ProcessOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessOrderJPanel
     */
    
    JPanel userProcessContainer;
    SoupWorkRequest request;
    EcoSystem system;
    UserAccount account;
    public ProcessOrderJPanel(JPanel userProcessContainer, SoupWorkRequest request, EcoSystem system,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system=system;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComplete = new javax.swing.JButton();

        btnComplete.setText("Complete Request");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(btnComplete)
                .addContainerGap(395, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        request.setStatus("Completed");
        for(Member mem:system.getMemberDirectory().getMemberList()){
            if(request.getMemName().equals(mem.getMemUsername())){
                for(SoupWorkRequest request : mem.getSoupRequestList()){
                    if(request.getStatus().equals("Assigned Field Worker")) {
                        request.setStatus("Completed");
                    }
                }
            }
        }
        for(DeliveryVolunteer volunteer : system.getDeliveryVolunteerDirectory().getVolunteerList()){
            if(volunteer.getVolunteerUsername().equals(account.getUsername())){
                volunteer.setAvailability(true);
            }
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    // End of variables declaration//GEN-END:variables
}
