/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AmbulanceRole;

import Business.Ambulance.Ambulance;
import Business.EcoSystem;
import Business.Member.Member;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sujay
 */
public class ProcessAmbulanceRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessAmbulanceRequestJPanel
     */
    JPanel userProcessContainer;
    EmergencyWorkRequest request;
    EcoSystem system;
    UserAccount account;
    
    public ProcessAmbulanceRequestJPanel(JPanel userProcessContainer, EmergencyWorkRequest request, EcoSystem system,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system=system;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComplete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComplete.setBackground(new java.awt.Color(133, 211, 255));
        btnComplete.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnComplete.setText("Pickup Completed");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 273, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ambulance.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 960, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        request.setStatus("Pickup Completed");
        for(Member mem:system.getMemberDirectory().getMemberList()){
            if(request.getMemName().equals(mem.getMemUsername())){
                for(EmergencyWorkRequest request : mem.getEmgRequestList()){
                    if(request.getStatus().equals("Assigned Ambulance")) {
                        request.setStatus("Pickup Completed");
                    }
                }
            }
        }
        for(Ambulance ambulance : system.getAmbulanceDirectory().getAmbulanceList()){
            if(ambulance.getAmbulanceUsername().equals(account.getUsername())){
                ambulance.setAvailability(true);
            }
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
